addons:
  apt:
    packages:
      - koji-client
      - librpm-dev
      - rpm

language: python
python:
  - "3.7"
install:
  - pip install tox
script:
  - tox

before_deploy: touch docs/_build/html/.nojekyll

deploy:
  provider: pages
  env: TOXENV=docs
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
  local_dir: docs/_build/html
